fn.err.li 1,14: `i` is duplicated
  > i
    ^
fn.err.li 2,10: unknown type `foo`
  > foo
    ^^^
fn.err.li 5,4: cannot use yield in function that return non-sequence type
  > yield '0'
    ^^^^^^^^^
fn.err.li 6,11: mismatched types: `string` (expected) and `int` (found)
  > i
    ^
fn.err.li 8,5: `g` is duplicated
  > g
    ^
fn.err.li 12,12: mismatched types: `string` (expected) and `int` (found)
  > v
    ^
fn.err.li 17,2: `v` is not function (`int`)
  > v()
    ^^^
fn.err.li 19,2: cannot call `int`
  > 0()
    ^^^
